// Objective-C API for talking to goprimes Go package.
//   gobind -lang=objc goprimes
//
// File is generated by gobind. Do not edit.

#ifndef __Goprimes_H__
#define __Goprimes_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT long GoprimesGoNThreads(long n, long threads);

#endif
