
// Objective-C API for talking to the following Go packages
//
//	goprimes
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Goprimes_FRAMEWORK_H__
#define __Goprimes_FRAMEWORK_H__

#include "Goprimes.objc.h"
#include "Universe.objc.h"

#endif
