[package]
name = "minimax"
version = "0.1.0"
authors = ["Guillermo Lella <arkorott@gmail.com>"]
edition = "2018"

[lib]
name = "minimax"
crate-type = ["lib", "staticlib"]

[dependencies]
libc = "0.2.86"
